apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore-app
  labels:
    type: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      type: webapp
  template:
    metadata:
      name: myapp-pod
      labels:
        type: webapp
    spec:
      containers:
        - name: mywebapp
          image: abhi9604/datastore:v1.0
